# docker-compose.yml
version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVER_TYPE: backend
    container_name: backend_server
    volumes:
      - ./config/backend-config:/app/config
    ports:
      - "8080:8080"  #HTTP

  ai:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVER_TYPE: ai
    container_name: ai_server
    volumes:
      - ./config/ai-config:/app/config
    ports:
      - "5000:5000"  #API

  cloud:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVER_TYPE: cloud
    container_name: cloud_server
    volumes:
      - ./config/cloud-config:/app/config
    ports:
      - "22:22"   #SSH