---
- name: apt update
  apt:
    update_cache: yes

- name: apt upgrade
  apt:
    upgrade: dist

- name: Install Docker
  apt:
    name: docker.io
    state: present
    update_cache: yes

- name: Check Docker version
  command: docker --version
  register: docker_version

- name: Display Docker version
  debug:
    msg: "Installed Docker version: {{ docker_version.stdout }}"


# Docker Compose 설치 (조건부로 모니터링 서버에서만)
- name: Install dependencies for Docker Compose (Debian)
  apt:
    name:
      - curl
      - jq
    state: present
    update_cache: yes
  when:
    - ansible_os_family == "Debian"
    - docker_compose_install == "yes"

- name: Download Docker Compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-{{ ansible_system }}-{{ ansible_machine }}"
    dest: /usr/local/bin/docker-compose
    mode: '0755'
  when: docker_compose_install == "yes"

- name: Create symbolic link for Docker Compose
  file:
    src: /usr/local/bin/docker-compose
    dest: /usr/bin/docker-compose
    state: link
  when: docker_compose_install == "yes"

- name: Check Docker Compose version
  command: docker-compose --version
  register: docker_compose_version_output
  when: docker_compose_install == "yes"

- name: Display Docker Compose version
  debug:
    msg: "Installed Docker Compose version: {{ docker_compose_version_output.stdout }}"
  when: docker_compose_install == "yes"