global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'docker-monitor'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'backend'
    static_configs:
      - targets: ['backend:8080']

  - job_name: 'ai'
    static_configs:
      - targets: ['ai:5000']

  - job_name: 'node-exporter'
    static_configs:
      - targets: [ 'localhost:9100' ]