---
- hosts: public
  vars_files:
    - public/vars.yml
  tasks:
    - import_tasks: public/tasks.yml
  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted

#- hosts: master
#  vars_files:
#    - common/vars.yml
#    - master/vars.yml
#  tasks:
#    - import_tasks: common/tasks.yml
#    - import_tasks: master/tasks.yml
#
#- hosts: worker
#  vars_files:
#    - common/vars.yml
#    - worker/vars.yml
#  tasks:
#    - import_tasks: common/tasks.yml
#    - import_tasks: worker/tasks.yml
#
#- hosts: ai
#  vars_files:
#    - common/vars.yml
#    - ai/vars.yml
#  tasks:
#    - import_tasks: common/tasks.yml
#    - import_tasks: ai/tasks.yml
