---
- hosts: public
  vars:
    docker_compose_install: "no"
  vars_files:
    - public/vars.yml
  tasks:
    - import_tasks: public/tasks.yml
  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted

- hosts: cloud
  vars:
    docker_compose_install: "yes"
  vars_files:
    - master/vars.yml
  tasks:
    - import_tasks: master/tasks.yml

- hosts: back
  vars:
    docker_compose_install: "no"
  vars_files:
    - worker/vars.yml
  tasks:
    - import_tasks: worker/tasks.yml

- hosts: ai
  vars:
    docker_compose_install: "no"
  vars_files:
    - ai/vars.yml
  tasks:
    - import_tasks: ai/tasks.yml